// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import CountdownTimerController from "./countdown_timer_controller"
application.register("countdown-timer", CountdownTimerController)

import FeedbackFormController from "./feedback_form_controller"
application.register("feedback-form", FeedbackFormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SweetalertController from "./sweetalert_controller"
application.register("sweetalert", SweetalertController)

import ToggleSwitchController from "./toggle_switch_controller"
application.register("toggle-switch", ToggleSwitchController)

import TwilioController from "./twilio_controller"
application.register("twilio", TwilioController)

import VideoCallSubscriptionController from "./video_call_subscription_controller"
application.register("video-call-subscription", VideoCallSubscriptionController)

import VideocardController from "./videocard_controller"
application.register("videocard", VideocardController)
